version: '3.8'

services:
  owlnextjs:
    image: node:14.17
    container_name: owlnextjs
    restart: always
    volumes:
      - .:/var/www
    ports:
      - 3000:3000
    working_dir: /var/www
    command: bash -c "npm install && npm run dev"
